services:
  server:
    build:
      context: ./server
    container_name: server
    networks:
      - conn_network
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    command: ./server

  client:
    build:
      context: ./client
    container_name: client
    networks:
      - conn_network
    depends_on:
      - server
    stdin_open: true
    tty: true
    command: /bin/sh

networks:
  conn_network:
    driver: bridge 
